apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  namespace: backend
  labels: 
    app: api
    role: api
spec:
  selector:
    matchLabels:
      app: api
  replicas: 1
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: api
          image: us-central1-docker.pkg.dev/exalted-crane-459000-g5/backend/backend-api:11
          ports:
          - containerPort: 8000
          env:
          - name: PORT
            value: "8000"