apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  namespace: app
  labels: 
    app: api
    role: api
spec:
  selector:
    matchLabels:
      app: api
  replicas: 1
  template:
    metadata:
      labels:
        app: api
    spec:
      serviceAccount: api-service-account
      containers:
        - name: api
          image: us-central1-docker.pkg.dev/exalted-crane-459000-g5/backend/backend-api:32
          ports:
          - containerPort: 8000
          env:
          - name: PORT
            value: "8000"
          - name: IS_SANDBOX
            value: "false"
          - name: KUBERNETES_NAMESPACE
            value: app
          - name: SANDBOX_IMAGE
            value: "us-central1-docker.pkg.dev/exalted-crane-459000-g5/backend/backend-api:32"
          - name: OPENAI_API_KEY
            valueFrom:
              secretKeyRef:
                name: api-secrets
                key: openai-api-key
          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 3
            timeoutSeconds: 5
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 15
            periodSeconds: 10
            timeoutSeconds: 5