apiVersion: apps/v1
kind: Deployment
metadata:
  name: front
  namespace: app
  labels: 
    app: front
    role: front
spec:
  selector:
    matchLabels:
      app: front
  replicas: 1
  template:
    metadata:
      labels:
        app: front
    spec:
      containers:
        - name: frontend
          image: us-central1-docker.pkg.dev/exalted-crane-459000-g5/frontend/frontend-app:9
          ports:
          - containerPort: 3000
          env:
          - name: PORT
            value: "3000"
          - name: NODE_ENV
            value: "production"
          - name: NEXT_PUBLIC_API_URL
            value: "http://api:8000"