apiVersion: v1
kind: Service
metadata:
  name: front
  namespace: app
  labels:
    app: front
spec:
  selector:
    app: front
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: ClusterIP