steps:
  - label: ":package: Build Backend Docker Image"
    commands:
      - echo "Bulding Fast API Docker Image"
      - cd api
      - docker buildx build -t sm01/cesarion:${C-1} -f Dockerfile .
      - docker push sm01/cesarion:${C-1}

  - label: ":package: Build Frontend Docker Image"
    commands:
      - echo "Building Next.js Docker Image"
      - cd frontend
      - docker build -t sm01/cesarion${C-1} -f Dockerfile .
      - docker push sm01/cesarion${C-1}
