apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app-ingress
  namespace: app
  annotations:
    kubernetes.io/ingress.global-static-ip-name: gke-cleo 
    networking.gke.io/managed-certificates: gke-certificate
    kubernetes.io/ingress.class: "gce"
    
    # nginx.ingress.kubernetes.io/rewrite-target: /
    # nginx.ingress.kubernetes.io/cors-allow-origin: "*"
    # nginx.ingress.kubernetes.io/cors-allow-methods: "GET, POST, PUT, DELETE, OPTIONS"
    # nginx.ingress.kubernetes.io/cors-allow-headers: "DNT,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Range,Authorization"
spec:
  ingressClassName: gce
  rules:
  - host: augustus.work
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: front
            port:
              number: 3000
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: api
            port:
              number: 8000
      - path: /sandboxes
        pathType: Prefix
        backend:
          service:
            name: api
            port:
              number: 8000
      - path: /execute
        pathType: Prefix
        backend:
          service:
            name: api
            port:
              number: 8000
  - host: www.augustus.work
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: front
            port:
              number: 3000
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: api
            port:
              number: 8000
      - path: /sandboxes
        pathType: Prefix
        backend:
          service:
            name: api
            port:
              number: 8000
      - path: /execute
        pathType: Prefix
        backend:
          service:
            name: api
            port:
              number: 8000

      